### ISSUE TITLE
Missed breakage in December 2022

### ISSUE THREAD

**Issue by RivenSkaye** [EmeraldSnorlax/manjarno#30]
On December 22nd, Manjaro's pacman mirrors were getting overwritten due to [an AUR package being preferred over their own repo's](https://github.com/msys2/MSYS2-packages/issues/3452) because someone over at the MSYS2 team pushed a (now renamed) [package with a colliding name](https://aur.archlinux.org/packages/msys2-pacman-mirrors). This was [reported publicly](https://www.reddit.com/r/ManjaroLinux/comments/zsv4mb/what_is_pacmanmirrors_doing_in_the_aur/) and the subsequent fix was asking the MSYS2 people to change the package name, as well as [changing the Manjaro package's name](https://www.reddit.com/r/ManjaroLinux/comments/zsv4mb/comment/j1b4if1/?utm_source=share&utm_medium=web2x&context=3) and subsequently [reverting the name change](https://gitlab.manjaro.org/applications/pacman-mirrors/-/issues/183) when the msys2 package was renamed.

~~I'm tempted to make a new `pacman-mirrorlist` package, but I'll refrain from doing so for now~~

**Comment by EmeraldSnorlax** [comment]
i might be missing something here, but i'm not sure this in scope for this article? it's a (as far as i can tell) relatively minor bug that neither party was directly responsible for, other than i guess a bug in pacman? i could very well be misunderstanding something here, though

i want to keep this as a list of repeated, structural and/or particularly egregious issues with manjaro, and from what i've read i'm not sure this fits. however, please feel free to give more information and your personal opinion if you feel otherwise

**Comment by RivenSkaye** [comment]
It's a few things, one of which at least fits in the structural problematic history.
- Pamac preferring (unsupported) AUR packages if they happen to have a higher version number
- the assumption that no AUR package will have a conflicting name
  - they even reverted the name change that would prevent this conflict from happening again
- This issue causing the mirrorlist to be overwritten with one that provides Windows binaries

**Comment by EmeraldSnorlax** [comment]
i'm willing to give them the benefit of the doubt here in my own subjective opinion here; i feel like this is a somewhat minor mistake in the grand scheme of things, but as always i welcome more discussion on this
