### ISSUE TITLE
About Manjaro and the AUR, and updates

### ISSUE THREAD

**Issue by KierPrev** [EmeraldSnorlax/manjarno#36]
It's important to recognize that any distribution can break, especially in the hands of those who enjoy tinkering with their systems. Damn, even my first Ubuntu installation was destroyed when I was first starting out with desktop Linux.

One of the most common complaints is that Manjaro delays packages for two weeks, but what people fail to mention is that this **only applies to specific branches**. It's important to take this into consideration before jumping to conclusions. For people that doesn't use the AUR, or just for an old AUR package, Stable branch is great!

The criticisms surrounding the AUR breakage problem have been blown out of proportion and lack context. In fact, problems are typically isolated to a single package, and **only occur if you use core system components from AUR**.

**Manjaro is a good starting point for beginners** who want to explore an Arch based like distro. Even if you, or me, use vanilla Arch or Arch-based.

It's crucial to exercise caution when using any Linux distribution and to avoid jumping to conclusions based on dispersed anecdotal evidence.

Thank you, and sorry for diving once again in the topic.

**Comment by theAkito** [comment]
> avoid jumping to conclusions based on anecdotal evidence.

With extremely complex & old, worn-out software, like popular operating systems, you mostly _can_ only rely on anecdotal evidence, simply due to the sheer complexity of such software.

Every computer hardware is different. Even if you use the same brands & models, a serial number can make the difference. Therefore, there is barely a way to reproducible "prove" something huge, like an operating system, will work. For example, lots of things work during Continuous Integration cycles, but when deployed can still cause issues due to unforeseen circumstances.

That said, there is nothing wrong with stating facts, even if the sources are based on Reddit posts featuring the official team behind the software. Everyone should know, that some Reddit posts are not an official announcement by the UN or something. It's just an online talk between a couple of nerds. And that's fine, when we are talking about open source projects of this type.

I think, honesty is generally extremely important. Same goes for the management of entire software development projects. If there are hints here & there, that a team isn't honest about how it works, what it achieves & especially what it did wrong, this is a red flag.

There are a couple of projects out there, where some people spread the truth about the downsides of something that was going on behind the scenes of that particular project & guess what - those posts get deleted as "off topic" or whatever. Every single time. Just to mute what needs to be said.

Then, a couple of web archived Reddit posts are usually all evidence you can gather. Always have your big ball of salt with you & you will probably come close to the truth of whatever matter is being discussed.



> It's important to recognize that any distribution can break, especially in the hands of those who enjoy tinkering with their systems. Damn, even my first Ubuntu installation was destroyed when I was first starting out with desktop Linux.

Comparing someone playing around with his own personal Linux distribution for learning purposes with a team of experts(?) running a fairly popular Linux distribution & repeatedly making avoidable mistakes - especially when we see in other open source Linux focused teams, that those mistakes are definitely avoidable - is, I think, not very valid.
The first one has almost no repsonsibility. The latter does, especially if the operating system is marketed as stable, good or perhaps even better than the one it is based on.

I saw so many people trying this distribution, because of all the marketing fuss it makes, through third parties etc. (Not actually paid marketing - I am talking about Linux articles & other people recommending it, etc.)

Those people usually run into issues, that never would've happened on the base distribution, because again, Manjaro did some weird shit, which broke something.

I've seen this for a long time. Told people to stop using any derivative & instead use the base operating system, which is actually fairly stable & problemless.

Then, after this, I found the website associated with this project. So, it's not even like I had to be convinced of anything, because it just confirmed, what I knew already. 😁



> **Manjaro is a good starting point for beginners** who want to explore an Arch based like distro. Even if you, or me, use vanilla Arch or Arch-based.

Based on what I said before, I object to that. It's maybe easier to get into, but in the long run you just experience these weird issues, that aren't there on the base distribution & in the worst case, people think "Arch sux; I'm going back to Ubuntu", when in fact Manjaro sux. Not Arch. 🙂

**Comment by KierPrev** [comment]
Thank you for your answer.
I have to kindly disagree with your points, but that's ok, it's part of human nature and the basis of society.
Ironic that I said that Manjaro is good for beginners, because myself, a GNU/Linux user for more than 15 years, have chosen to use Manjaro, mostly due to its release cycle (3~4 weeks), and its package availability.  (Also, pacman doesn't suck), with the added benefit of not having to babysit my OS.

Anyway, to each their own.
Manjaro stands on the grounds of a solid project, Archlinux, and I hope it remains that way for a long time.
